name: Go

on:
  pull_request:
  push:
    branches: ["main"]

env:
  GO_VERSION: "1.22"

jobs:
  integration-test:
    runs-on: ubuntu-latest
    name: Integration tests
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Hurl
        run: |
          curl -LO https://github.com/Orange-OpenSource/hurl/releases/download/5.0.0/hurl_5.0.0_amd64.deb
          sudo dpkg -i hurl_5.0.0_amd64.deb
          hurl --version
      - name: Integration test
        run: bin/integration.sh http://loca
